name: flutter_sample
description: My sample of Flutter app.

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ^2.0.1

dependencies:
  cupertino_icons: ^1.0.2
  file_picker: ^2.0.3
  flutter:
    sdk: flutter
  flutter_image_compress: ^0.7.0
  flutter_state_notifier: ^0.7.0
  flutter_svg: ^0.19.0
  freezed_annotation: ^0.12.0
  mime: ^1.0.0
  native_pdf_view: ^3.8.0
  provider: ^5.0.0-nullsafety.5
  state_notifier: ^0.7.0

dependency_overrides:
  # https://github.com/fluttercandies/extended_image/issues/258
  extended_image: 1.5.0-dev

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  freezed: any
  pedantic_mono: any

flutter:

  uses-material-design: true

  assets:
    - assets/
