name: flutter_sample
description: My sample of Flutter app.

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ^1.17.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  flutter_svg: ^0.19.0

  file_picker: ^2.0.3
  mime: ^0.9.7
  flutter_image_compress: ^0.7.0
  native_pdf_view: ^3.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
